--Karmienia 
use KarmieniaZwierzat;
insert into Karmienia (Pracownik, Posilek, godzina,dzien) values (17, 7, '8:21:00', '7/26/2018');
insert into KarmieniaBoksow(Karmienie, Boks) values (IDENT_CURRENT('Karmienia'), 'AB001');
insert into Karmienia (Pracownik, Posilek, godzina,dzien) values (23, 9, '9:01 PM', '7/26/2018');
insert into KarmieniaBoksow(Karmienie, Boks) values (IDENT_CURRENT('Karmienia'), 'AB003');
insert into Karmienia (Pracownik, Posilek, godzina,dzien) values (23, 1, '8:53 PM', '7/26/2018');
insert into KarmieniaBoksow(Karmienie, Boks) values (IDENT_CURRENT('Karmienia'), 'AB002');
insert into Karmienia (Pracownik, Posilek, godzina,dzien) values (22, 15, '4:05 PM', '7/26/2018');
insert into KarmieniaZwierzat(Karmienie, numer,gatunek) values (IDENT_CURRENT('Karmienia'), '001' ,'Fennek' );
insert into Karmienia (Pracownik, Posilek, godzina,dzien) values (4, 6, '6:07 AM', '7/26/2018');
insert into KarmieniaBoksow(Karmienie, Boks) values (IDENT_CURRENT('Karmienia'), 'AB002');
insert into Karmienia (Pracownik, Posilek, godzina,dzien) values (25, 4, '9:26 PM', '7/26/2018');
insert into KarmieniaBoksow(Karmienie, Boks) values (IDENT_CURRENT('Karmienia'), 'AB005');
insert into Karmienia (Pracownik, Posilek, godzina,dzien) values (2, 6, '3:29 PM', '7/26/2018');
insert into KarmieniaBoksow(Karmienie, Boks) values (IDENT_CURRENT('Karmienia'), 'AB008');
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (25, 20, '5:50 AM', '7/26/2018');
insert into KarmieniaZwierzat(Karmienie, numer,gatunek) values (IDENT_CURRENT('Karmienia'), '001' ,'Gereza' );
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (24, 8, '11:00 PM', '7/26/2018');
insert into KarmieniaBoksow(Karmienie, Boks) values (IDENT_CURRENT('Karmienia'), 'AB003');
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (8, 8, '6:16 PM', '7/26/2018');
insert into KarmieniaBoksow(Karmienie, Boks) values (IDENT_CURRENT('Karmienia'), 'AB007');
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (25, 19, '12:46 AM', '7/26/2018');
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (15, 5, '6:39 PM', '7/26/2018');
insert into KarmieniaBoksow(Karmienie, Boks) values (IDENT_CURRENT('Karmienia'), 'AB008');
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (1, 5, '8:05 PM', '1/25/2018');
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (13, 12, '1:18 AM', '1/25/2018');
insert into KarmieniaZwierzat(Karmienie, numer,gatunek) values (IDENT_CURRENT('Karmienia'), '001' ,'Ryœ' );
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (18, 5, '5:09 PM', '1/24/2018');
insert into KarmieniaBoksow(Karmienie, Boks) values (IDENT_CURRENT('Karmienia'), 'AB006');
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (29, 2, '9:46 AM', '2/24/2018');
insert into KarmieniaBoksow(Karmienie, Boks) values (IDENT_CURRENT('Karmienia'), 'AB007');
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (19, 11, '10:30 PM', '9/26/2018');
insert into KarmieniaZwierzat(Karmienie, numer,gatunek) values (IDENT_CURRENT('Karmienia'), '1' ,'Panda Ma³a' );
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (7, 15, '7:24 AM', '9/4/2018');
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (9, 20, '1:31 PM', '1/22/2018');
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (1, 17, '4:38 AM', '5/6/2018');
insert into KarmieniaZwierzat(Karmienie, numer,gatunek) values (IDENT_CURRENT('Karmienia'), '1' ,'Zebra' );
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (6, 14, '5:44 AM', '2/6/2018');
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (26, 17, '5:11 AM', '10/4/2018');
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (24, 6, '8:34 AM', '10/14/2018');
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (20, 18, '12:53 PM', '3/21/2018');
insert into KarmieniaZwierzat(Karmienie, numer,gatunek) values (IDENT_CURRENT('Karmienia'), '1' ,'Lew' );
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (25, 8, '11:51 PM', '12/15/2017');
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (9, 2, '5:22 AM', '5/29/2018');
insert into KarmieniaZwierzat(Karmienie, numer,gatunek) values (IDENT_CURRENT('Karmienia'), '2' ,'Lew' );
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (15, 17, '10:33 AM', '5/13/2018');
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (3, 6, '1:06 PM', '4/23/2018');
insert into KarmieniaBoksow(Karmienie, Boks) values (IDENT_CURRENT('Karmienia'), 'AB004');
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (29, 9, '12:00 PM', '9/17/2018');
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (20, 13, '8:00 AM', '8/9/2018');
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (6, 3, '1:54 AM', '11/5/2018');
insert into KarmieniaZwierzat(Karmienie, numer,gatunek) values (IDENT_CURRENT('Karmienia'), '1' ,'Panda Ma³a' );
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (23, 15, '8:12 PM', '9/13/2018');
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (22, 2, '9:36 AM', '12/29/2017');
insert into KarmieniaBoksow(Karmienie, Boks) values (IDENT_CURRENT('Karmienia'), 'AB005');
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (1, 8, '3:35 PM', '9/4/2018');
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (19, 19, '7:39 PM', '3/2/2018');
insert into KarmieniaZwierzat(Karmienie, numer,gatunek) values (IDENT_CURRENT('Karmienia'), '1' ,'Fennek' );
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (25, 2, '12:46 AM', '3/19/2018');
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (30, 8, '1:37 PM', '3/30/2018');
insert into KarmieniaZwierzat(Karmienie, numer,gatunek) values (IDENT_CURRENT('Karmienia'), '1' ,'Fennek' );
insert into Karmienia (Pracownik, Posilek, godzina, dzien) values (5, 18, '5:58 AM', '4/9/2018');

insert into ModyfikacjePosilkow(Karmienie , Skladnik , ilosc , Uzasadnienie) values ('5', 'Baranina', 6, 'Brak Wo³owiny');
insert into ModyfikacjePosilkow(Karmienie , Skladnik , ilosc , Uzasadnienie) values ('15', 'Nektarynki', 1.5, 'Brak Bananów - zamiast tego 0.5 kg wiecej nektarynek');
insert into ModyfikacjePosilkow(Karmienie , Skladnik , ilosc , Uzasadnienie) values ('1', 'Mix zieleniny', 2, 'Brak Bananów - zamiast tego Zielenina');
insert into ModyfikacjePosilkow(Karmienie , Skladnik , ilosc , Uzasadnienie) values ('13', 'Baranina', 4, 'Brak Wo³owiny');
insert into ModyfikacjePosilkow(Karmienie , Skladnik , ilosc , Uzasadnienie) values ('17', 'Baranina', 6, 'Brak Wo³owiny');
insert into ModyfikacjePosilkow(Karmienie , Skladnik , ilosc , Uzasadnienie) values ('9', 'Nektarynki', 1, 'Brak Lisci Bambusa');
insert into ModyfikacjePosilkow(Karmienie , Skladnik , ilosc , Uzasadnienie) values ('11', 'Nektarynki', 1.5, 'Brak Cytrusów');
insert into ModyfikacjePosilkow(Karmienie , Skladnik , ilosc , Uzasadnienie) values ('22', 'Jagody', 0, 'Brak jagód i ich substytutu');
insert into ModyfikacjePosilkow(Karmienie , Skladnik , ilosc , Uzasadnienie) values ('3', 'Baranina', 0.5, 'Brak Jaszczurek , podano baranine');
insert into ModyfikacjePosilkow(Karmienie , Skladnik , ilosc , Uzasadnienie) values ('19', 'Leki', 0.20, 'Nakaz lekarza - zmienjszenie dawki');

--select * from Boksy;
--select * from Diety;
--select * from Gatunki;
--select * from Zwierzeta;
--select * from KarmieniaBoksow;
--select * from KarmieniaZwierzat;
--select * from Karmienia;
--select * from ModyfikacjePosilkow;
--select * from Posilki;
--select * from Pracownicy;
--select * from Skladniki;
--select * from Sklady_Posilkow
--select * from Weterynarze;
--select * from ZlecenieDiety;

